# Generated by Django 4.1.3 on 2023-11-12 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=datetime.date(2023, 11, 12))),
                ('updated_date', models.DateTimeField(default=datetime.date(2023, 11, 12))),
                ('scheduled_date', models.DateTimeField(default=None)),
            ],
        ),
    ]
